# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QuQuyetCT0vY1nbz8F9GARcipf50TfSR
"""

data = {
'Fever': [101, 98.6, 100, 103, 99, 102, 97.5, 101.5, 98.2, 164],
'BodyPain': [1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
'Age': [25, 48, 35, 28, 60, 18, 50, 33, 45, 22],
'Illness': [1, 0, 1, 1, 0, 1, 0, 1, 0, 1]
}

import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.DataFrame(data)

df.info()
X = df[['Fever', 'BodyPain', 'Age']]
y = df['Illness']

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=42)

data = pd.read_csv('zareef.csv')
data.head()

# data.drop(columns=['Previous_Medication'],inplace=True)

data['Previous_Medication'].value_counts()

data.isnull().sum()

data['Previous_Medication'].fillna('None',inplace=True)

data['Previous_Medication'].value_counts()

data.info()

data.isnull().sum()

data['Previous_Medication']

from sklearn.preprocessing import LabelEncoder

categorical_columns=['Gender','Age','Headache','Body_Ache','Fatigue','Chronic_Conditions','Temperature','BMI','Allergies','Humidity','AQI','Alcohol_Consumption','Physical_Activity','Diet_Type','Heart_Rate','Blood_Pressure','Recommended_Medication','Previous_Medication','Smoking_History']
label_encoders = {}
for column in categorical_columns:
    label_encoder = LabelEncoder()
    data[column] = label_encoder.fit_transform(data[column])
    label_encoders[column] = label_encoder
    le_target=LabelEncoder()
data['Fever_Severity']=le_target.fit_transform(data['Fever_Severity'])

data.head()

data.info()

# data['Previous_medication'].replace({'ibuprofen':0,'parcetamol':1,'Aspirin':2,'None':3,inplace=True})
# for manually adding previous medication

import matplotlib.pyplot as plt
import seaborn as sns

corr_matrix=data.corr()
print(corr_matrix)

plt.figure(figsize=(16,10))
sns.heatmap(corr_matrix,annot=True,cmap='coolwarm',fmt="0.0")
plt.title("Correlation heatmap")

